// 109 cities served by JL Masonry across Massachusetts.
// Each entry has the local context needed to generate UNIQUE programmatic SEO copy
// per city × service combo (architecture, soil, climate, neighborhoods, history).

export type CityRegion =
  | "MetroWest"
  | "Greater Boston"
  | "South Suburban"
  | "North Shore"
  | "Central MA";

export type City = {
  slug: string;
  name: string;
  state: "MA";
  region: CityRegion;
  county: string;
  population: string;
  neighborhoods: string[];
  architectureStyle: string;
  soilNote: string;
  climateNote: string;
  localProof: string;
  nearbyLandmark: string;
  zip: string;
};

export const cities: City[] = [
  // === METROWEST (50) ===
  { slug: "marlborough", name: "Marlborough", state: "MA", region: "MetroWest", county: "Middlesex", population: "41,800", neighborhoods: ["Hillside", "Robin Hill", "French Hill"], architectureStyle: "Colonial Revivals and 1980s split-levels", soilNote: "Glacial till with rocky subsoil — drainage tile essential", climateNote: "Heavy freeze-thaw cycles from December to March", localProof: "Many homes built between 1950–1990 with original chimneys due for repointing", nearbyLandmark: "Solomon Pond and the Assabet River corridor", zip: "01752" },
  { slug: "hudson", name: "Hudson", state: "MA", region: "MetroWest", county: "Middlesex", population: "20,000", neighborhoods: ["Centro", "Houghton Hills", "Quinn Park"], architectureStyle: "Victorian downtown homes and post-war Capes", soilNote: "Loamy soils over ledge in upland areas", climateNote: "Late-spring frosts common; pour windows are tight", localProof: "Many Portuguese-American homes with traditional stone walls", nearbyLandmark: "Assabet River Rail Trail", zip: "01749" },
  { slug: "framingham", name: "Framingham", state: "MA", region: "MetroWest", county: "Middlesex", population: "72,000", neighborhoods: ["Saxonville", "Nobscot", "Lokerville"], architectureStyle: "Mixed: Victorian, Tudor, mid-century ranches, modern subdivisions", soilNote: "Mixed loam and clay; expansive clay around Cochituate", climateNote: "Significant precipitation; downspout-to-grade tie-ins critical", localProof: "Older Saxonville mill houses still relying on stone foundations", nearbyLandmark: "Cushing Memorial Park and Garden in the Woods", zip: "01701" },
  { slug: "westborough", name: "Westborough", state: "MA", region: "MetroWest", county: "Worcester", population: "21,500", neighborhoods: ["Lyman Street", "Lake Chauncy", "Bowman Lane"], architectureStyle: "High-end Colonial and Tudor estates", soilNote: "Glacial till with significant boulders — challenging for footings", climateNote: "Open exposure to NW winter winds", localProof: "Newer (1995+) homes often need chimney crown work after 25+ winters", nearbyLandmark: "Lake Chauncy and Westborough Reservoir", zip: "01581" },
  { slug: "northborough", name: "Northborough", state: "MA", region: "MetroWest", county: "Worcester", population: "15,800", neighborhoods: ["Brigham Street", "Whitney Street", "Edmund Hill"], architectureStyle: "Colonial Revival and contemporary farmhouse", soilNote: "Sandy loam over glacial deposits", climateNote: "Cold snaps below 0°F three to four nights per winter", localProof: "Many original 1700s stone walls along property lines", nearbyLandmark: "Mount Pisgah Conservation Area", zip: "01532" },
  { slug: "southborough", name: "Southborough", state: "MA", region: "MetroWest", county: "Worcester", population: "10,500", neighborhoods: ["Fayville", "Cordaville", "Pine Hill"], architectureStyle: "Estate Colonials and 18th-century farmhouses", soilNote: "Rocky upland with intermittent ledge", climateNote: "Higher elevation = heavier snow load on chimneys", localProof: "Historic 1700s walls running along Main Street", nearbyLandmark: "St. Mark's School campus", zip: "01772" },
  { slug: "shrewsbury", name: "Shrewsbury", state: "MA", region: "MetroWest", county: "Worcester", population: "39,000", neighborhoods: ["Edgemere", "Bouder Brook", "Holden Street"], architectureStyle: "Mid-century ranches transitioning to upscale Colonials", soilNote: "Sandy loam, well-drained near Lake Quinsigamond", climateNote: "Lake effect creates morning fog and damp masonry", localProof: "Many lakefront properties with seawalls and retaining walls", nearbyLandmark: "Lake Quinsigamond", zip: "01545" },
  { slug: "natick", name: "Natick", state: "MA", region: "MetroWest", county: "Middlesex", population: "37,000", neighborhoods: ["Natick Center", "Felchville", "South Natick"], architectureStyle: "Victorian downtown and post-war neighborhoods", soilNote: "Clay-heavy near Lake Cochituate; drainage critical", climateNote: "Mild but wet; mortar joints take a beating", localProof: "Original Henry Wilson-era homes with stone foundations", nearbyLandmark: "Lake Cochituate State Park", zip: "01760" },
  { slug: "ashland", name: "Ashland", state: "MA", region: "MetroWest", county: "Middlesex", population: "18,800", neighborhoods: ["Downtown Ashland", "Howe Street", "Pleasant Street"], architectureStyle: "Capes, ranches, and new construction Colonials", soilNote: "Loamy with stone outcrops; clean base prep needed", climateNote: "Subject to Sudbury River valley freeze pockets", localProof: "Mill-era foundations along the Sudbury River", nearbyLandmark: "Ashland State Park and Reservoir", zip: "01721" },
  { slug: "sudbury", name: "Sudbury", state: "MA", region: "MetroWest", county: "Middlesex", population: "18,800", neighborhoods: ["Wayside Inn", "Sherman's Bridge", "Hop Brook"], architectureStyle: "Colonial Revival estates and 1980s subdivisions", soilNote: "Glacial till with high water table in low areas", climateNote: "Wet springs require careful patio drainage planning", localProof: "Multi-acre lots with extensive stone walls to maintain", nearbyLandmark: "Wayside Inn (oldest operating in the US)", zip: "01776" },
  { slug: "hopkinton", name: "Hopkinton", state: "MA", region: "MetroWest", county: "Middlesex", population: "18,800", neighborhoods: ["Woodville", "Hopkinton Center", "Lake Maspenock"], architectureStyle: "Large-lot Colonials and luxury new construction", soilNote: "Rocky glacial till; expensive excavation for footings", climateNote: "Highest elevations in MetroWest = harsher freeze-thaw", localProof: "Hopkinton hosts the Boston Marathon start — high-visibility properties", nearbyLandmark: "Hopkinton State Park", zip: "01748" },
  { slug: "milford", name: "Milford", state: "MA", region: "MetroWest", county: "Worcester", population: "30,000", neighborhoods: ["Plains", "Hayward Field", "Bear Hill"], architectureStyle: "Italianate Victorians and dense triple-deckers", soilNote: "Granite-rich subsoil — actual quarry country", climateNote: "Heavy clay belts in southern sections of town", localProof: "Pink Milford Granite used in landmark buildings across MA", nearbyLandmark: "Milford Town Hall (granite landmark)", zip: "01757" },
  { slug: "wayland", name: "Wayland", state: "MA", region: "MetroWest", county: "Middlesex", population: "14,000", neighborhoods: ["Cochituate", "Wayland Center", "Happy Hollow"], architectureStyle: "Custom Colonials and 1960s contemporaries", soilNote: "Sandy loam over glacial sand deposits", climateNote: "Lake effect from Lake Cochituate impacts moisture levels", localProof: "Mid-century modern homes with original masonry hearths", nearbyLandmark: "Sudbury Valley Trustees conservation land", zip: "01778" },
  { slug: "holliston", name: "Holliston", state: "MA", region: "MetroWest", county: "Middlesex", population: "15,000", neighborhoods: ["Holliston Center", "Mudville", "Braggville"], architectureStyle: "1700s-1800s Federal homes and Colonial Revivals", soilNote: "Rocky with significant boulders in northern town", climateNote: "Cold valley pockets along Charles River headwaters", localProof: "Historic district with original brick and granite work", nearbyLandmark: "Upper Charles River Reservation", zip: "01746" },
  { slug: "grafton", name: "Grafton", state: "MA", region: "MetroWest", county: "Worcester", population: "20,300", neighborhoods: ["Grafton Common", "Saundersville", "North Grafton"], architectureStyle: "Colonial Common-era and farmhouse styles", soilNote: "Loam over compact till; level pads possible", climateNote: "Moderate snowfall; chimney flashing leaks common after storms", localProof: "Tufts Veterinary School-adjacent properties value clean curb appeal", nearbyLandmark: "Grafton Town Common with original stonework", zip: "01519" },
  { slug: "clinton", name: "Clinton", state: "MA", region: "MetroWest", county: "Worcester", population: "13,800", neighborhoods: ["High Street", "Beacon Hill", "Lancaster Mills"], architectureStyle: "Brick mill housing and 3-story Victorians", soilNote: "Tight urban lots over fill from the mill era", climateNote: "Wachusett Reservoir microclimate keeps it cool", localProof: "Brick chimney rebuilds extremely common on triple-deckers", nearbyLandmark: "Wachusett Reservoir Dam", zip: "01510" },
  { slug: "maynard", name: "Maynard", state: "MA", region: "MetroWest", county: "Middlesex", population: "10,800", neighborhoods: ["Mill District", "Downtown Maynard", "Glenwood"], architectureStyle: "Mill-era brick blocks and worker housing", soilNote: "Sandy along Assabet River; clay uphill", climateNote: "Damp riverside conditions accelerate mortar weathering", localProof: "Original 1840s mill stonework still visible downtown", nearbyLandmark: "Assabet River Walk", zip: "01754" },
  { slug: "stow", name: "Stow", state: "MA", region: "MetroWest", county: "Middlesex", population: "7,400", neighborhoods: ["Lower Village", "Pompositticut", "Gleasondale"], architectureStyle: "1700s Colonials and orchard-country farmhouses", soilNote: "Glacial till with sandy patches", climateNote: "Apple country = open exposure and wind", localProof: "Stone walls outline original colonial farmland parcels", nearbyLandmark: "Honey Pot Hill Orchards", zip: "01775" },
  { slug: "acton", name: "Acton", state: "MA", region: "MetroWest", county: "Middlesex", population: "23,500", neighborhoods: ["West Acton", "South Acton", "North Acton"], architectureStyle: "Capes, Garrison Colonials, and contemporary glass-front", soilNote: "Sandy outwash plains, some bedrock outcrops", climateNote: "Wide temperature swings between night and day", localProof: "Many properties built in 1960–80 still on original chimneys", nearbyLandmark: "Nashoba Brook Conservation Land", zip: "01720" },
  { slug: "concord", name: "Concord", state: "MA", region: "MetroWest", county: "Middlesex", population: "19,700", neighborhoods: ["West Concord", "Concord Center", "Conantum"], architectureStyle: "Federal-era homes, 1800s Italianates, and modernist", soilNote: "Alluvial silt near rivers; rocky uplands", climateNote: "River fog increases damp on masonry north faces", localProof: "Historical district enforcement requires period-correct stonework", nearbyLandmark: "Walden Pond", zip: "01742" },
  { slug: "berlin", name: "Berlin", state: "MA", region: "MetroWest", county: "Worcester", population: "3,300", neighborhoods: ["Berlin Center", "Pleasant Street area", "South Berlin"], architectureStyle: "Rural farmhouses and small Capes", soilNote: "Rocky soils with field stone abundant", climateNote: "Higher elevation = harsher winter exposure", localProof: "Many active old-growth stone walls along farm boundaries", nearbyLandmark: "Mount Pisgah Conservation Area", zip: "01503" },
  { slug: "bolton", name: "Bolton", state: "MA", region: "MetroWest", county: "Worcester", population: "5,600", neighborhoods: ["Bolton Center", "Still River", "Wattaquadock"], architectureStyle: "1700s farmhouses and modern luxury custom homes", soilNote: "Apple-country rocky loam over till", climateNote: "Open hilltop properties face NW wind chill", localProof: "Bolton apple orchards bordered by colonial stone walls", nearbyLandmark: "Bolton Town Common", zip: "01740" },
  { slug: "lincoln", name: "Lincoln", state: "MA", region: "MetroWest", county: "Middlesex", population: "7,000", neighborhoods: ["Lincoln Center", "South Lincoln", "Beaver Pond"], architectureStyle: "Mid-century modernist (Gropius House country) plus Colonials", soilNote: "Loam over tight till", climateNote: "Forested microclimate retains moisture", localProof: "Architecturally protected — masonry must match original character", nearbyLandmark: "Walden Pond / DeCordova Sculpture Park", zip: "01773" },
  { slug: "weston", name: "Weston", state: "MA", region: "MetroWest", county: "Middlesex", population: "11,800", neighborhoods: ["Weston Center", "Highland", "Sears Land"], architectureStyle: "High-end Colonials, Tudors, and stone-clad estates", soilNote: "Rocky upland with hand-laid wall traditions", climateNote: "Higher elevation than surrounding towns = colder", localProof: "Many estates feature professional-grade hardscape from 1920s–40s", nearbyLandmark: "Weston Reservoir", zip: "02493" },
  { slug: "wellesley", name: "Wellesley", state: "MA", region: "MetroWest", county: "Norfolk", population: "29,000", neighborhoods: ["Wellesley Hills", "Wellesley Square", "Cliff Estates"], architectureStyle: "Estate Tudors, Colonials, and luxury custom builds", soilNote: "Clay-rich soils require careful drainage on flat lots", climateNote: "Established trees mean lots of leaf litter on hardscape", localProof: "Wellesley homes routinely feature custom brick and bluestone walks", nearbyLandmark: "Wellesley College campus", zip: "02481" },
  { slug: "needham", name: "Needham", state: "MA", region: "MetroWest", county: "Norfolk", population: "32,000", neighborhoods: ["Needham Heights", "Birds Hill", "Charles River Village"], architectureStyle: "Colonials, Garrisons, and renovated mid-century", soilNote: "Glacial till with moderate drainage", climateNote: "Charles River fog affects north-facing masonry", localProof: "Massive teardown-rebuild boom — fresh masonry on most new construction", nearbyLandmark: "Charles River and Cutler Park", zip: "02492" },
  { slug: "dover", name: "Dover", state: "MA", region: "MetroWest", county: "Norfolk", population: "5,900", neighborhoods: ["Dover Center", "Farm Street", "Pegan Hill"], architectureStyle: "Estate-scale Colonials, stone manors, horse properties", soilNote: "Rocky with significant boulder removal needs", climateNote: "Rural temperatures run several degrees cooler than Boston", localProof: "Dover historically requires top-tier masonry on most properties", nearbyLandmark: "Noanet Woodlands", zip: "02030" },
  { slug: "medfield", name: "Medfield", state: "MA", region: "MetroWest", county: "Norfolk", population: "13,200", neighborhoods: ["Medfield Center", "West Street", "Harding Estates"], architectureStyle: "Federal Colonials and 1990s subdivisions", soilNote: "Wet meadows in low areas; tile drainage essential", climateNote: "Charles River valley = damp summers, cold winters", localProof: "Many Medfield Historical District homes need period-matching mortar", nearbyLandmark: "Rocky Narrows Reservation", zip: "02052" },
  { slug: "millis", name: "Millis", state: "MA", region: "MetroWest", county: "Norfolk", population: "8,500", neighborhoods: ["Millis Center", "West Millis", "South Millis"], architectureStyle: "Small Capes and modest Colonials", soilNote: "Sandy loam with occasional ledge", climateNote: "Charles River microclimate", localProof: "Many original 1950s suburban homes need walkway and stoop rebuilds", nearbyLandmark: "Charles River Stony Brook Reservation", zip: "02054" },
  { slug: "sherborn", name: "Sherborn", state: "MA", region: "MetroWest", county: "Middlesex", population: "4,200", neighborhoods: ["Sherborn Center", "Whitney Hill", "Brush Hill"], architectureStyle: "Equestrian estates and rural Colonials", soilNote: "Glacial till with mature trees demanding root-zone care", climateNote: "Open rural temperature swings", localProof: "Two-acre minimum zoning = expansive driveways and walls", nearbyLandmark: "Rocky Narrows Reservation", zip: "01770" },
  { slug: "boxborough", name: "Boxborough", state: "MA", region: "MetroWest", county: "Middlesex", population: "5,500", neighborhoods: ["Boxborough Center", "Liberty Square", "Hill Road area"], architectureStyle: "1980s Colonials and rural farmhouses", soilNote: "Rocky uplands with significant ledge", climateNote: "Higher elevation, exposed to NW winds", localProof: "Many homes built 1985–95 need chimney crown replacement", nearbyLandmark: "Beaver Brook Conservation Land", zip: "01719" },
  { slug: "boylston", name: "Boylston", state: "MA", region: "MetroWest", county: "Worcester", population: "4,800", neighborhoods: ["Boylston Center", "Hillside", "Sewall Street"], architectureStyle: "Rural Colonials around Wachusett Reservoir", soilNote: "Sandy with rocky outcrops", climateNote: "Reservoir microclimate moderates extremes", localProof: "Reservoir watershed regulations require careful site work", nearbyLandmark: "Wachusett Reservoir", zip: "01505" },
  { slug: "west-boylston", name: "West Boylston", state: "MA", region: "MetroWest", county: "Worcester", population: "7,800", neighborhoods: ["West Boylston Center", "Oakdale", "Holbrook Pond"], architectureStyle: "Mid-century ranches and modest Colonials", soilNote: "Sandy with ledge in elevated sections", climateNote: "Wachusett Reservoir mist common in fall", localProof: "Many original 1950s-60s walkways and stoops nearing end of life", nearbyLandmark: "Wachusett Reservoir Dam", zip: "01583" },
  { slug: "holden", name: "Holden", state: "MA", region: "MetroWest", county: "Worcester", population: "19,800", neighborhoods: ["Holden Center", "Jefferson", "Chaffins"], architectureStyle: "1960s-80s Colonials and split-levels", soilNote: "Rocky uplands; full excavation common for new walls", climateNote: "Elevation = significant snowfall and ice dams", localProof: "Holden's hilly terrain creates frequent retaining wall needs", nearbyLandmark: "Wachusett Mountain area", zip: "01520" },
  { slug: "sterling", name: "Sterling", state: "MA", region: "MetroWest", county: "Worcester", population: "8,000", neighborhoods: ["Sterling Center", "Chocksett", "East Sterling"], architectureStyle: "Rural Colonials, farmhouses, and horse properties", soilNote: "Rocky farm soils with abundant fieldstone", climateNote: "Wachusett Mountain exposure", localProof: "Apple-orchard heritage means many original stone walls", nearbyLandmark: "Sholan Farms and Sterling Common", zip: "01564" },
  { slug: "lancaster", name: "Lancaster", state: "MA", region: "MetroWest", county: "Worcester", population: "8,200", neighborhoods: ["Lancaster Center", "South Lancaster", "Bartlett Pond"], architectureStyle: "Federal-era homes and rural Colonials", soilNote: "Loam with rocky outcrops along Nashua River", climateNote: "Cold river valley pockets", localProof: "Oldest town in Worcester County with 1600s stonework still standing", nearbyLandmark: "Bartlett Pond and Atlantic Union College area", zip: "01523" },
  { slug: "harvard", name: "Harvard", state: "MA", region: "MetroWest", county: "Worcester", population: "6,900", neighborhoods: ["Harvard Center", "Still River", "Bare Hill"], architectureStyle: "Estate Colonials, historic farmsteads, modernist customs", soilNote: "Glacial till with apple-orchard soils", climateNote: "Hilltop exposure to strong winter wind", localProof: "Many homes have period-correct stone walls from the 1700s-1800s", nearbyLandmark: "Fruitlands Museum", zip: "01451" },
  { slug: "upton", name: "Upton", state: "MA", region: "MetroWest", county: "Worcester", population: "8,000", neighborhoods: ["Upton Center", "Pratt Pond", "West Hill"], architectureStyle: "Small-town Colonials and modest Capes", soilNote: "Rocky with significant fieldstone deposits", climateNote: "Inland cold pockets in winter", localProof: "Local granite quarry tradition makes natural-stone walls a heritage choice", nearbyLandmark: "Upton State Forest", zip: "01568" },
  { slug: "mendon", name: "Mendon", state: "MA", region: "MetroWest", county: "Worcester", population: "6,300", neighborhoods: ["Mendon Center", "South Mendon", "Northbridge Road area"], architectureStyle: "Rural farmhouses and modern luxury builds", soilNote: "Loam over till; some clay near wetlands", climateNote: "Open rural exposure to wind", localProof: "Southwick's Zoo-adjacent area with mature stone walls", nearbyLandmark: "Southwick's Zoo and Inman Hill", zip: "01756" },
  { slug: "hopedale", name: "Hopedale", state: "MA", region: "MetroWest", county: "Worcester", population: "6,000", neighborhoods: ["Hopedale Center", "Hopedale Pond area", "Adin Street"], architectureStyle: "Italianate Victorians and mill-era brick housing", soilNote: "Sandy along Mill River; clay uphill", climateNote: "Pond microclimate generates humidity in summer", localProof: "Draper Mill heritage means abundant 1800s brick and granite", nearbyLandmark: "Hopedale Pond", zip: "01747" },
  { slug: "littleton", name: "Littleton", state: "MA", region: "MetroWest", county: "Middlesex", population: "10,300", neighborhoods: ["Littleton Common", "Long Lake", "Nagog Hill"], architectureStyle: "Capes, ranches, and luxury new construction", soilNote: "Glacial outwash sands and gravels", climateNote: "Long Lake provides cooling lake effect", localProof: "Many 1700s-1800s walls along Nashoba Valley orchards", nearbyLandmark: "Nashoba Valley Ski Area", zip: "01460" },
  { slug: "westford", name: "Westford", state: "MA", region: "MetroWest", county: "Middlesex", population: "25,000", neighborhoods: ["Westford Center", "Graniteville", "Forge Village"], architectureStyle: "Colonial Revival and luxury Colonials", soilNote: "Granite-rich (literally named Graniteville)", climateNote: "Elevation creates wind exposure", localProof: "Westford granite was historically quarried for foundations across MA", nearbyLandmark: "Westford Town Common", zip: "01886" },
  { slug: "carlisle", name: "Carlisle", state: "MA", region: "MetroWest", county: "Middlesex", population: "5,400", neighborhoods: ["Carlisle Center", "Greenough Pond", "Hutchins Farm area"], architectureStyle: "Two-acre estate Colonials and farmhouses", soilNote: "Glacial till with mature woods", climateNote: "Forested microclimate retains snowpack longer", localProof: "Strict zoning = larger, more visible hardscape projects", nearbyLandmark: "Estabrook Woods", zip: "01741" },
  { slug: "chelmsford", name: "Chelmsford", state: "MA", region: "MetroWest", county: "Middlesex", population: "36,000", neighborhoods: ["Chelmsford Center", "North Chelmsford", "South Chelmsford"], architectureStyle: "Mid-century Capes, ranches, and 1980s Colonials", soilNote: "Sandy outwash with ledge in upland areas", climateNote: "Cooler than Boston by 2-3 degrees year-round", localProof: "Many original 1950s-70s walkways and stoops nearing end of service life", nearbyLandmark: "Russell Mill Pond", zip: "01824" },
  { slug: "groton", name: "Groton", state: "MA", region: "MetroWest", county: "Middlesex", population: "11,300", neighborhoods: ["Groton Center", "Lost Lake", "West Groton"], architectureStyle: "Federal-era Colonials and contemporary builds", soilNote: "Rocky with significant fieldstone resources", climateNote: "Higher elevation = harsher freeze-thaw", localProof: "Many properties feature mature stone wall systems requiring repair", nearbyLandmark: "Lawrence Academy and Groton School", zip: "01450" },
  { slug: "ayer", name: "Ayer", state: "MA", region: "MetroWest", county: "Middlesex", population: "8,500", neighborhoods: ["Ayer Center", "Pingryville", "Snake Hill"], architectureStyle: "Compact downtown Victorians and mid-century homes", soilNote: "Sandy outwash on Nashoba aquifer", climateNote: "Inland chill in winter", localProof: "Fort Devens proximity drives steady demand for foundation work", nearbyLandmark: "Fort Devens", zip: "01432" },
  { slug: "shirley", name: "Shirley", state: "MA", region: "MetroWest", county: "Middlesex", population: "7,200", neighborhoods: ["Shirley Center", "Shirley Village", "Squannacook"], architectureStyle: "Federal Colonials and modest 20th-century homes", soilNote: "Sandy along Squannacook River; rockier uphill", climateNote: "Rural temperatures swing dramatically", localProof: "Historic district enforcement requires careful material matching", nearbyLandmark: "Squannacook River", zip: "01464" },
  { slug: "lunenburg", name: "Lunenburg", state: "MA", region: "MetroWest", county: "Worcester", population: "11,800", neighborhoods: ["Lunenburg Center", "Whalom", "Lake Whalom area"], architectureStyle: "Lakefront Cape Cods and rural Colonials", soilNote: "Mixed sand and till; lake-adjacent areas wetter", climateNote: "Lake Whalom moderates summer heat", localProof: "Lakeshore stone walls and seawalls common", nearbyLandmark: "Lake Whalom", zip: "01462" },
  { slug: "medway", name: "Medway", state: "MA", region: "MetroWest", county: "Norfolk", population: "13,200", neighborhoods: ["Medway Center", "Rabbit Hill", "West Medway"], architectureStyle: "1980s-90s Colonials and contemporary subdivisions", soilNote: "Clay-rich in lowlands; rocky uphill", climateNote: "Charles River headwaters create damp conditions", localProof: "Many newer-build subdivisions facing first-time masonry repairs", nearbyLandmark: "Charles River and Choate Park", zip: "02053" },
  { slug: "norfolk", name: "Norfolk", state: "MA", region: "MetroWest", county: "Norfolk", population: "11,500", neighborhoods: ["Norfolk Center", "City Mills", "Pondville"], architectureStyle: "Suburban Colonials and modest Capes", soilNote: "Mixed; clay in low areas, sandy uphill", climateNote: "Stop Sign Town - rural feel with cold pockets", localProof: "Many homes have original 1980s walkways needing rebuild", nearbyLandmark: "Stony Brook Reservation area", zip: "02056" },

  // === GREATER BOSTON (19) ===
  { slug: "lexington", name: "Lexington", state: "MA", region: "Greater Boston", county: "Middlesex", population: "34,500", neighborhoods: ["Lexington Center", "East Lexington", "Pierce's Bridge"], architectureStyle: "Historic Federal, Colonial Revival, and contemporary luxury", soilNote: "Glacial till with mature tree cover", climateNote: "Cooler than central Boston by 1-2 degrees", localProof: "Strict historic district requires period-correct mortar matching", nearbyLandmark: "Lexington Battle Green", zip: "02420" },
  { slug: "bedford", name: "Bedford", state: "MA", region: "Greater Boston", county: "Middlesex", population: "13,800", neighborhoods: ["Bedford Center", "Springs Brook", "Davis Road"], architectureStyle: "Mid-century Capes and modern Colonials", soilNote: "Sandy outwash with some ledge", climateNote: "Hanscom Field proximity = open exposure", localProof: "Many properties feature 1950s-70s stone walls needing repointing", nearbyLandmark: "Minuteman National Historical Park", zip: "01730" },
  { slug: "burlington", name: "Burlington", state: "MA", region: "Greater Boston", county: "Middlesex", population: "26,400", neighborhoods: ["Burlington Center", "Pine Hill", "Bedford Street"], architectureStyle: "1960s-80s suburban with major teardown-rebuild activity", soilNote: "Mixed glacial till", climateNote: "Slightly warmer due to urban heat island near Route 3", localProof: "Many original 1960s split-levels getting modern hardscape upgrades", nearbyLandmark: "Burlington Mall and Mary Cummings Park", zip: "01803" },
  { slug: "waltham", name: "Waltham", state: "MA", region: "Greater Boston", county: "Middlesex", population: "65,000", neighborhoods: ["Waltham Center", "South Side", "Lakeview"], architectureStyle: "Victorian, triple-decker, Colonial Revival, and modern condo", soilNote: "Urban fill, clay near Charles River", climateNote: "Charles River fog affects masonry north faces", localProof: "Brandeis area and Waverly Oaks feature mature stonework", nearbyLandmark: "Charles River and Brandeis University", zip: "02452" },
  { slug: "newton", name: "Newton", state: "MA", region: "Greater Boston", county: "Middlesex", population: "88,000", neighborhoods: ["Newton Centre", "West Newton", "Newton Highlands", "Auburndale"], architectureStyle: "Estate Tudors, Victorians, and high-end Colonial Revivals", soilNote: "Glacial till with significant clay layers", climateNote: "Multiple village centers with varied microclimates", localProof: "Newton's 13 villages feature some of the finest historic masonry in MA", nearbyLandmark: "Crystal Lake and Boston College campus", zip: "02458" },
  { slug: "brookline", name: "Brookline", state: "MA", region: "Greater Boston", county: "Norfolk", population: "60,000", neighborhoods: ["Coolidge Corner", "Brookline Village", "Chestnut Hill"], architectureStyle: "Brick rowhouses, Tudors, and stone mansions", soilNote: "Urban with significant clay; dense old root systems", climateNote: "Urban heat island offset by tree-lined streets", localProof: "Brookline's 1800s brick and granite stocks need ongoing repointing", nearbyLandmark: "Larz Anderson Park and Reservoir", zip: "02445" },
  { slug: "cambridge", name: "Cambridge", state: "MA", region: "Greater Boston", county: "Middlesex", population: "118,000", neighborhoods: ["Harvard Square", "Cambridgeport", "Mid-Cambridge"], architectureStyle: "Federal-era brick, Victorian triple-decker, and modern", soilNote: "Urban fill, clay, often poor drainage", climateNote: "Charles River microclimate; salt damage from winter roads", localProof: "Among the densest historic masonry inventory in the country", nearbyLandmark: "Harvard and MIT campuses", zip: "02139" },
  { slug: "somerville", name: "Somerville", state: "MA", region: "Greater Boston", county: "Middlesex", population: "81,000", neighborhoods: ["Davis Square", "Union Square", "Winter Hill"], architectureStyle: "Triple-decker, Victorian, and modern infill", soilNote: "Urban fill with clay; deep granite footings", climateNote: "Dense urban heat island", localProof: "Triple-decker chimneys are everywhere and almost all need work", nearbyLandmark: "Davis Square and Tufts University", zip: "02143" },
  { slug: "medford", name: "Medford", state: "MA", region: "Greater Boston", county: "Middlesex", population: "59,000", neighborhoods: ["Medford Square", "West Medford", "South Medford"], architectureStyle: "Victorian, triple-decker, and Colonial Revival", soilNote: "Urban with clay; Mystic River alluvial in lowlands", climateNote: "River fog impacts north-facing masonry", localProof: "Medford has a high concentration of original 1900s brick chimneys", nearbyLandmark: "Mystic River and Tufts University", zip: "02155" },
  { slug: "malden", name: "Malden", state: "MA", region: "Greater Boston", county: "Middlesex", population: "60,000", neighborhoods: ["Malden Center", "Maplewood", "Edgeworth"], architectureStyle: "Dense triple-decker, Victorian, and brick commercial", soilNote: "Urban fill with poor natural drainage", climateNote: "Urban island; salt damage common", localProof: "Many original 1900s chimneys at the end of service life", nearbyLandmark: "Pine Banks Park", zip: "02148" },
  { slug: "melrose", name: "Melrose", state: "MA", region: "Greater Boston", county: "Middlesex", population: "29,000", neighborhoods: ["Melrose Center", "Wyoming", "Cedar Park"], architectureStyle: "Victorian, Colonial Revival, and Tudor", soilNote: "Urban with clay; some rocky upland", climateNote: "Sheltered by surrounding hills", localProof: "Melrose's historic district enforces material standards", nearbyLandmark: "Middlesex Fells Reservation", zip: "02176" },
  { slug: "wakefield", name: "Wakefield", state: "MA", region: "Greater Boston", county: "Middlesex", population: "27,000", neighborhoods: ["Wakefield Center", "Greenwood", "Montrose"], architectureStyle: "Victorian, Colonial, and mid-century ranch", soilNote: "Lakeside clay; rockier uphill", climateNote: "Lake Quannapowitt moderates temperature", localProof: "Lakefront walls and historic downtown brick", nearbyLandmark: "Lake Quannapowitt", zip: "01880" },
  { slug: "reading", name: "Reading", state: "MA", region: "Greater Boston", county: "Middlesex", population: "25,500", neighborhoods: ["Reading Center", "North Reading line", "Birch Meadow"], architectureStyle: "Colonial Revival, Victorian, and Capes", soilNote: "Mixed glacial till", climateNote: "Slightly cooler than Boston due to elevation", localProof: "Strong residential market keeps masonry upgrade demand high", nearbyLandmark: "Reading Town Common", zip: "01867" },
  { slug: "stoneham", name: "Stoneham", state: "MA", region: "Greater Boston", county: "Middlesex", population: "23,500", neighborhoods: ["Stoneham Center", "Pine Banks", "Spot Pond area"], architectureStyle: "Capes, ranches, and Colonial Revivals", soilNote: "Rocky around Middlesex Fells; clay in valleys", climateNote: "Fells elevation moderates temperatures", localProof: "Many homes feature original 1950s walkways and stoops at end of life", nearbyLandmark: "Spot Pond and Middlesex Fells", zip: "02180" },
  { slug: "woburn", name: "Woburn", state: "MA", region: "Greater Boston", county: "Middlesex", population: "40,000", neighborhoods: ["West Woburn", "Four Corners", "North Woburn"], architectureStyle: "Mixed: Victorian downtown, Capes, ranches, and modern", soilNote: "Mixed urban fill and glacial till", climateNote: "Slightly cooler than central Boston", localProof: "JL Masonry's home base — fastest response time, deepest local knowledge", nearbyLandmark: "Horn Pond and Whispering Hill", zip: "01801" },
  { slug: "winchester", name: "Winchester", state: "MA", region: "Greater Boston", county: "Middlesex", population: "23,000", neighborhoods: ["Winchester Center", "Symmes Corner", "Winchester Highlands"], architectureStyle: "Estate Tudors, Colonial Revivals, and luxury custom", soilNote: "Rocky uphill, clay in valleys", climateNote: "Winchester reservoirs create damp microclimate", localProof: "High-end residential market values period-correct stonework", nearbyLandmark: "Mystic Lakes and Winchester Country Club", zip: "01890" },
  { slug: "arlington", name: "Arlington", state: "MA", region: "Greater Boston", county: "Middlesex", population: "46,000", neighborhoods: ["Arlington Heights", "Arlington Center", "East Arlington"], architectureStyle: "Victorian, Colonial, and modern triple-decker", soilNote: "Urban fill with clay; Mystic Valley wetter", climateNote: "Sheltered by surrounding hills", localProof: "Heights area features extensive mature stone wall systems", nearbyLandmark: "Spy Pond and the Minuteman Bikeway", zip: "02474" },
  { slug: "belmont", name: "Belmont", state: "MA", region: "Greater Boston", county: "Middlesex", population: "27,500", neighborhoods: ["Belmont Center", "Belmont Hill", "Cushing Square"], architectureStyle: "Estate Tudors, Colonial Revivals, and Victorian", soilNote: "Rocky on Belmont Hill; clay in valleys", climateNote: "Belmont Hill elevation = cooler temperatures", localProof: "Belmont Hill features some of the area's finest historic masonry", nearbyLandmark: "Belmont Hill School and Habitat", zip: "02478" },
  { slug: "watertown", name: "Watertown", state: "MA", region: "Greater Boston", county: "Middlesex", population: "35,000", neighborhoods: ["Watertown Square", "East Watertown", "Coolidge Hill"], architectureStyle: "Triple-decker, Colonial Revival, and Victorian", soilNote: "Urban with clay; Charles River alluvial nearby", climateNote: "Charles River microclimate", localProof: "Mt. Auburn Cemetery area features outstanding historic stonework", nearbyLandmark: "Mt. Auburn Cemetery and Charles River", zip: "02472" },

  // === SOUTH SUBURBAN (15) ===
  { slug: "quincy", name: "Quincy", state: "MA", region: "South Suburban", county: "Norfolk", population: "101,000", neighborhoods: ["Wollaston", "Quincy Center", "Squantum"], architectureStyle: "Dense triple-decker, Victorian, and waterfront condos", soilNote: "Urban fill, clay, coastal sand", climateNote: "Coastal humidity accelerates mortar weathering", localProof: "Quincy granite is the literal source of NYC's Bunker Hill Monument", nearbyLandmark: "Adams National Historical Park", zip: "02169" },
  { slug: "braintree", name: "Braintree", state: "MA", region: "South Suburban", county: "Norfolk", population: "39,000", neighborhoods: ["Braintree Center", "South Braintree", "Five Corners"], architectureStyle: "Capes, ranches, and Colonials", soilNote: "Glacial till with clay deposits", climateNote: "Coastal influence in eastern sections", localProof: "South Shore commuter zone with steady masonry upgrade demand", nearbyLandmark: "South Shore Plaza", zip: "02184" },
  { slug: "weymouth", name: "Weymouth", state: "MA", region: "South Suburban", county: "Norfolk", population: "57,000", neighborhoods: ["North Weymouth", "South Weymouth", "Jackson Square"], architectureStyle: "Capes, ranches, and Victorian seaside cottages", soilNote: "Coastal sand near the harbor; rocky inland", climateNote: "Coastal salt air affects mortar", localProof: "Naval Air Station heritage drives ongoing residential development", nearbyLandmark: "Weymouth Back River", zip: "02188" },
  { slug: "milton", name: "Milton", state: "MA", region: "South Suburban", county: "Norfolk", population: "28,000", neighborhoods: ["Milton Center", "East Milton", "Brush Hill"], architectureStyle: "Estate Tudors, Colonial Revivals, and Victorian", soilNote: "Rocky on Blue Hills slopes; clay in valleys", climateNote: "Blue Hills create cooler temperatures", localProof: "Milton Hill features outstanding historic stonework", nearbyLandmark: "Blue Hills Reservation", zip: "02186" },
  { slug: "canton", name: "Canton", state: "MA", region: "South Suburban", county: "Norfolk", population: "24,000", neighborhoods: ["Canton Center", "Ponkapoag", "Pleasant Street"], architectureStyle: "Colonial Revival, Cape, and luxury custom", soilNote: "Sandy with rocky outcrops near Blue Hills", climateNote: "Blue Hills shelter from north winds", localProof: "Many properties feature extensive 1980s-90s hardscape needing refresh", nearbyLandmark: "Ponkapoag Pond and Blue Hills", zip: "02021" },
  { slug: "randolph", name: "Randolph", state: "MA", region: "South Suburban", county: "Norfolk", population: "34,000", neighborhoods: ["Randolph Center", "North Randolph", "Crawford Square"], architectureStyle: "Capes, ranches, and modest Colonials", soilNote: "Mixed glacial till", climateNote: "Cooler than coastal towns due to inland location", localProof: "Working-class neighborhoods with high demand for cost-effective masonry", nearbyLandmark: "Powers Farm Conservation", zip: "02368" },
  { slug: "stoughton", name: "Stoughton", state: "MA", region: "South Suburban", county: "Norfolk", population: "29,000", neighborhoods: ["Stoughton Center", "Dry Pond", "West Stoughton"], architectureStyle: "Capes, ranches, and Colonials", soilNote: "Sandy outwash with rocky upland", climateNote: "Inland cool with summer humidity", localProof: "Mature 1960s-80s neighborhoods need significant masonry refresh", nearbyLandmark: "Ames Pond", zip: "02072" },
  { slug: "sharon", name: "Sharon", state: "MA", region: "South Suburban", county: "Norfolk", population: "18,500", neighborhoods: ["Sharon Center", "Lake Massapoag", "Glendale"], architectureStyle: "Mid-century Colonials and contemporary builds", soilNote: "Sandy near the lake; rocky uphill", climateNote: "Lake Massapoag creates moisture", localProof: "Lake Massapoag retaining walls common around homes", nearbyLandmark: "Lake Massapoag", zip: "02067" },
  { slug: "walpole", name: "Walpole", state: "MA", region: "South Suburban", county: "Norfolk", population: "25,000", neighborhoods: ["Walpole Center", "East Walpole", "South Walpole"], architectureStyle: "Capes, Colonials, and luxury new builds", soilNote: "Mixed clay and sand", climateNote: "Inland temperatures with humid summers", localProof: "Strong residential demand with growing luxury custom market", nearbyLandmark: "Adirondack chair country and Bird Park", zip: "02081" },
  { slug: "foxborough", name: "Foxborough", state: "MA", region: "South Suburban", county: "Norfolk", population: "18,500", neighborhoods: ["Foxborough Center", "West Foxborough", "Lakeview"], architectureStyle: "Colonials, Capes, and luxury custom near Patriot Place", soilNote: "Glacial till with significant boulders", climateNote: "Inland cool with summer thunderstorms", localProof: "Stadium-area residential growth drives masonry demand", nearbyLandmark: "Gillette Stadium and Patriot Place", zip: "02035" },
  { slug: "dedham", name: "Dedham", state: "MA", region: "South Suburban", county: "Norfolk", population: "25,500", neighborhoods: ["Dedham Square", "Riverdale", "Oakdale"], architectureStyle: "Colonial Revival, Tudor, and Victorian", soilNote: "Urban with clay along Charles River", climateNote: "Charles River microclimate", localProof: "Dedham's historic district enforces premium masonry standards", nearbyLandmark: "Charles River and Dedham Town Common", zip: "02026" },
  { slug: "norwood", name: "Norwood", state: "MA", region: "South Suburban", county: "Norfolk", population: "29,000", neighborhoods: ["Norwood Center", "South Norwood", "Westover"], architectureStyle: "Colonials, Capes, and Victorian downtown", soilNote: "Mixed glacial till", climateNote: "Inland cool, snowy winters", localProof: "Strong middle-class residential base with steady masonry demand", nearbyLandmark: "Norwood Town Common and Hawes Pool", zip: "02062" },
  { slug: "franklin", name: "Franklin", state: "MA", region: "South Suburban", county: "Norfolk", population: "33,000", neighborhoods: ["Franklin Center", "Unionville", "Beaver Pond"], architectureStyle: "Colonials, Capes, and modern subdivisions", soilNote: "Rocky uplands with clay in low areas", climateNote: "Inland cold pockets in winter", localProof: "Significant 1990s-2000s subdivision growth = first-time masonry refresh", nearbyLandmark: "Beaver Pond and Charles River headwaters", zip: "02038" },
  { slug: "bellingham", name: "Bellingham", state: "MA", region: "South Suburban", county: "Norfolk", population: "16,500", neighborhoods: ["Bellingham Center", "North Bellingham", "Crooks Corner"], architectureStyle: "Capes, ranches, and modest Colonials", soilNote: "Mixed clay and rocky upland", climateNote: "Inland cold and humid summers", localProof: "Working-class community with high demand for honest, cost-effective masonry", nearbyLandmark: "Silver Lake", zip: "02019" },
  { slug: "wrentham", name: "Wrentham", state: "MA", region: "South Suburban", county: "Norfolk", population: "12,000", neighborhoods: ["Wrentham Center", "Sheldonville", "Plainville line"], architectureStyle: "Capes, Colonials, and rural farmhouses", soilNote: "Rocky with significant fieldstone", climateNote: "Inland temperature swings", localProof: "Many original 1700s-1800s stone walls along property lines", nearbyLandmark: "Wrentham Outlets and Lake Pearl", zip: "02093" },

  // === NORTH SHORE (6) ===
  { slug: "lynn", name: "Lynn", state: "MA", region: "North Shore", county: "Essex", population: "101,000", neighborhoods: ["Lynn Center", "Highlands", "Wyoma"], architectureStyle: "Dense triple-decker, Victorian, and waterfront condos", soilNote: "Coastal sand near beach; rocky uplands", climateNote: "Coastal humidity and winter storm exposure", localProof: "Hundreds of original 1900s brick chimneys ready for rebuild", nearbyLandmark: "Lynn Heritage State Park and Lynn Beach", zip: "01902" },
  { slug: "saugus", name: "Saugus", state: "MA", region: "North Shore", county: "Essex", population: "28,000", neighborhoods: ["Saugus Center", "Cliftondale", "East Saugus"], architectureStyle: "Capes, ranches, and Colonial Revival", soilNote: "Mixed coastal and inland soils", climateNote: "Coastal salt exposure", localProof: "Saugus Ironworks heritage means historic granite and brickwork", nearbyLandmark: "Saugus Ironworks National Historic Site", zip: "01906" },
  { slug: "peabody", name: "Peabody", state: "MA", region: "North Shore", county: "Essex", population: "54,500", neighborhoods: ["Peabody Center", "West Peabody", "South Peabody"], architectureStyle: "Capes, ranches, Victorian downtown, and modern", soilNote: "Mixed glacial till with clay in low areas", climateNote: "Coastal influence with inland cool winters", localProof: "Many mid-century neighborhoods in masonry refresh cycle", nearbyLandmark: "Brooksby Farm", zip: "01960" },
  { slug: "salem", name: "Salem", state: "MA", region: "North Shore", county: "Essex", population: "44,500", neighborhoods: ["Downtown Salem", "Salem Willows", "South Salem"], architectureStyle: "Federal-era brick, Victorian, and historic colonial", soilNote: "Coastal urban with clay and fill", climateNote: "Coastal salt and humidity", localProof: "Some of the oldest masonry in America still standing here", nearbyLandmark: "House of the Seven Gables", zip: "01970" },
  { slug: "beverly", name: "Beverly", state: "MA", region: "North Shore", county: "Essex", population: "42,000", neighborhoods: ["Beverly Farms", "Centerville", "Montserrat"], architectureStyle: "Seaside cottages, Victorian, and estate Colonials", soilNote: "Coastal sand and ledge", climateNote: "Coastal salt air", localProof: "Beverly Farms features outstanding seaside-stone estate work", nearbyLandmark: "Beverly Harbor and Lynch Park", zip: "01915" },
  { slug: "danvers", name: "Danvers", state: "MA", region: "North Shore", county: "Essex", population: "28,000", neighborhoods: ["Danvers Center", "Tapleyville", "Putnamville"], architectureStyle: "Colonial Revival, Cape, and modern subdivisions", soilNote: "Mixed glacial till with rocky outcrops", climateNote: "Coastal-adjacent with inland cool winters", localProof: "Strong residential market with steady masonry demand", nearbyLandmark: "Endicott Park", zip: "01923" },

  // === CENTRAL MA (19) ===
  { slug: "worcester", name: "Worcester", state: "MA", region: "Central MA", county: "Worcester", population: "206,500", neighborhoods: ["Burncoat", "Tatnuck", "West Side"], architectureStyle: "Dense triple-decker, Victorian, brick commercial, and modern", soilNote: "Urban fill, clay, and granite bedrock", climateNote: "Snowiest major city in MA — heavy ice and freeze-thaw", localProof: "Massive historic masonry stock — Worcester is a brick-and-granite city", nearbyLandmark: "Worcester Common and Polar Park", zip: "01608" },
  { slug: "auburn", name: "Auburn", state: "MA", region: "Central MA", county: "Worcester", population: "16,500", neighborhoods: ["Auburn Center", "Drury Square", "Pondville"], architectureStyle: "Capes, ranches, and Colonial Revival", soilNote: "Glacial till with rocky areas", climateNote: "Inland cold; significant snowfall", localProof: "Many mid-century neighborhoods in masonry refresh cycle", nearbyLandmark: "Auburn Mall", zip: "01501" },
  { slug: "millbury", name: "Millbury", state: "MA", region: "Central MA", county: "Worcester", population: "13,500", neighborhoods: ["Millbury Center", "Bramanville", "West Millbury"], architectureStyle: "Mill-era housing and rural Colonials", soilNote: "Mixed with significant clay near Blackstone River", climateNote: "River valley dampness", localProof: "Mill-era brick stock from the 1800s in need of repointing", nearbyLandmark: "Blackstone River and Singletary Lake", zip: "01527" },
  { slug: "sutton", name: "Sutton", state: "MA", region: "Central MA", county: "Worcester", population: "9,500", neighborhoods: ["Sutton Center", "Manchaug", "Wilkinsonville"], architectureStyle: "Rural Colonials and farmhouse styles", soilNote: "Rocky with abundant fieldstone", climateNote: "Hilltop exposure to NW winter winds", localProof: "Many 1700s-1800s stone walls still in active use", nearbyLandmark: "Purgatory Chasm State Reservation", zip: "01590" },
  { slug: "oxford", name: "Oxford", state: "MA", region: "Central MA", county: "Worcester", population: "14,000", neighborhoods: ["Oxford Center", "Rochdale", "North Oxford"], architectureStyle: "Capes, ranches, and rural farmhouses", soilNote: "Sandy outwash with rocky uplands", climateNote: "Inland cool with humid summers", localProof: "Working-class community with strong demand for honest masonry", nearbyLandmark: "Hodges Village Dam", zip: "01540" },
  { slug: "webster", name: "Webster", state: "MA", region: "Central MA", county: "Worcester", population: "17,000", neighborhoods: ["Webster Center", "Sandersdale", "Lake Webster area"], architectureStyle: "Mill-era housing and lakefront cottages", soilNote: "Sandy near Lake Webster", climateNote: "Lake effect creates fog and damp", localProof: "Lakefront walls and seawalls common — granite specialty area", nearbyLandmark: "Lake Chargoggagoggmanchauggagoggchaubunagungamaugg", zip: "01570" },
  { slug: "leicester", name: "Leicester", state: "MA", region: "Central MA", county: "Worcester", population: "11,000", neighborhoods: ["Leicester Center", "Cherry Valley", "Rochdale"], architectureStyle: "Rural farmhouses and modest Colonials", soilNote: "Rocky uplands with fieldstone abundance", climateNote: "Hilltop elevation = harsh winters", localProof: "Becker College area features extensive historic stonework", nearbyLandmark: "Greenville Pond and Becker College", zip: "01524" },
  { slug: "spencer", name: "Spencer", state: "MA", region: "Central MA", county: "Worcester", population: "11,800", neighborhoods: ["Spencer Center", "East Spencer", "Wire Village"], architectureStyle: "Rural Colonials and 1800s mill housing", soilNote: "Rocky with fieldstone", climateNote: "Hilltop exposure", localProof: "Many original 1800s farms with extensive stone wall systems", nearbyLandmark: "Spencer State Forest", zip: "01562" },
  { slug: "charlton", name: "Charlton", state: "MA", region: "Central MA", county: "Worcester", population: "13,000", neighborhoods: ["Charlton City", "Charlton Center", "Charlton Depot"], architectureStyle: "Rural farmhouses and contemporary builds", soilNote: "Rocky with significant fieldstone deposits", climateNote: "Inland cold; significant snow", localProof: "Active farming community with extensive original stone walls", nearbyLandmark: "Pine Acres Family Camp area", zip: "01507" },
  { slug: "dudley", name: "Dudley", state: "MA", region: "Central MA", county: "Worcester", population: "11,500", neighborhoods: ["Dudley Center", "South Dudley", "Quinebaug"], architectureStyle: "Mill-era housing and rural Colonials", soilNote: "Sandy near rivers; rocky uplands", climateNote: "River valley dampness", localProof: "Many 1800s mill-era brick chimneys nearing rebuild age", nearbyLandmark: "Nichols College and French River", zip: "01571" },
  { slug: "northbridge", name: "Northbridge", state: "MA", region: "Central MA", county: "Worcester", population: "16,000", neighborhoods: ["Whitinsville", "Riverdale", "Linwood"], architectureStyle: "Mill-era housing and Victorian downtown", soilNote: "Sandy along Mumford River; rocky uphill", climateNote: "River microclimate", localProof: "Whitin Machine Works heritage means abundant 1800s brick", nearbyLandmark: "Lookout Rock Reservation", zip: "01588" },
  { slug: "uxbridge", name: "Uxbridge", state: "MA", region: "Central MA", county: "Worcester", population: "14,000", neighborhoods: ["Uxbridge Center", "North Uxbridge", "South Uxbridge"], architectureStyle: "Mill-era housing and rural Colonials", soilNote: "Sandy along Blackstone River; rocky uphill", climateNote: "River dampness", localProof: "Blackstone River heritage with significant historic masonry", nearbyLandmark: "Blackstone River and Canal Heritage Park", zip: "01569" },
  { slug: "douglas", name: "Douglas", state: "MA", region: "Central MA", county: "Worcester", population: "9,000", neighborhoods: ["Douglas Center", "East Douglas", "West Douglas"], architectureStyle: "Rural Colonials and farmhouses", soilNote: "Rocky with significant fieldstone", climateNote: "Hilltop exposure to NW winter winds", localProof: "Many original 1700s-1800s stone wall systems intact", nearbyLandmark: "Douglas State Forest", zip: "01516" },
  { slug: "blackstone", name: "Blackstone", state: "MA", region: "Central MA", county: "Worcester", population: "9,200", neighborhoods: ["Blackstone Center", "Millville line", "Branch"], architectureStyle: "Mill-era housing and Capes", soilNote: "Sandy along Blackstone River", climateNote: "River dampness", localProof: "Mill heritage means abundant 1800s brick masonry", nearbyLandmark: "Blackstone River Canal Trail", zip: "01504" },
  { slug: "paxton", name: "Paxton", state: "MA", region: "Central MA", county: "Worcester", population: "4,800", neighborhoods: ["Paxton Center", "Asnebumskit", "Holden line"], architectureStyle: "Rural Colonials and modest Capes", soilNote: "Rocky hilltop soils", climateNote: "Asnebumskit Hill = highest elevation in central MA", localProof: "Many homes on dramatic slopes need engineered retaining walls", nearbyLandmark: "Moore State Park", zip: "01612" },
  { slug: "rutland", name: "Rutland", state: "MA", region: "Central MA", county: "Worcester", population: "8,200", neighborhoods: ["Rutland Center", "North Rutland", "Pleasantdale"], architectureStyle: "Rural Colonials and farmhouses", soilNote: "Rocky uplands; abundant fieldstone", climateNote: "Highest-elevation town in central MA = harshest winters", localProof: "Wachusett Reservoir watershed protection rules apply", nearbyLandmark: "Rutland State Park", zip: "01543" },
  { slug: "princeton", name: "Princeton", state: "MA", region: "Central MA", county: "Worcester", population: "3,500", neighborhoods: ["Princeton Center", "East Princeton", "Wachusett Mountain area"], architectureStyle: "Rural Colonials and modern luxury custom", soilNote: "Rocky with significant ledge", climateNote: "Highest elevation = harshest winters in MA", localProof: "Wachusett Mountain proximity creates unique microclimate", nearbyLandmark: "Wachusett Mountain State Reservation", zip: "01541" },
  { slug: "leominster", name: "Leominster", state: "MA", region: "Central MA", county: "Worcester", population: "43,800", neighborhoods: ["Leominster Center", "North Leominster", "West Leominster"], architectureStyle: "Mill-era housing, Victorian, and modern", soilNote: "Mixed urban and rocky uplands", climateNote: "Inland cold and snowy", localProof: "Significant historic brick masonry inventory", nearbyLandmark: "Sholan Farms and Doyle Field", zip: "01453" },
  { slug: "fitchburg", name: "Fitchburg", state: "MA", region: "Central MA", county: "Worcester", population: "41,000", neighborhoods: ["Fitchburg Center", "Cleghorn", "Crocker Field"], architectureStyle: "Dense triple-decker, mill-era brick, and Victorian", soilNote: "Urban with clay; rocky uplands", climateNote: "Inland cold; significant snowfall", localProof: "Major historic mill city with extensive brick masonry inventory", nearbyLandmark: "Fitchburg State University and Coggshall Park", zip: "01420" },
];

// Index by slug for fast lookup
export const citiesBySlug = new Map(cities.map((c) => [c.slug, c]));

// Group by region
export function citiesByRegion() {
  const grouped: Record<CityRegion, City[]> = {
    MetroWest: [],
    "Greater Boston": [],
    "South Suburban": [],
    "North Shore": [],
    "Central MA": [],
  };
  for (const c of cities) grouped[c.region].push(c);
  return grouped;
}
