// Extended service metadata used by programmatic SEO pages.
// Pairs with the `services` list in lib/site.ts (matching slugs).

export type ServiceMeta = {
  slug: string;
  shortLabel: string;
  longLabel: string;
  searchPhrase: string; // "patio installation" / "stone wall builder"
  searchPhrasePlural: string;
  problems: string[]; // common issues homeowners face
  materials: string[];
  durationTypical: string;
  costRange: string;
  bestSeason: string;
  lifespan: string;
  regulatoryNote: string;
  inspectionPoints: string[];
  whyNow: string;
  faqs: Array<{ q: string; a: string }>;
};

export const serviceMeta: ServiceMeta[] = [
  {
    slug: "patios",
    shortLabel: "Patio",
    longLabel: "Custom Stone & Paver Patios",
    searchPhrase: "patio builder",
    searchPhrasePlural: "patios",
    problems: [
      "Existing patio is heaving, settling, or cracking after freeze-thaw cycles",
      "Old concrete slab is stained, pitted, or has separated joints",
      "Pavers have shifted, sunk, or grown weeds in the joints",
      "Outdoor space drains toward the house instead of away",
      "Backyard has no usable surface for dining, fire pit, or seating",
    ],
    materials: [
      "Bluestone (Pennsylvania)",
      "Granite cobble and slab",
      "Concrete pavers (Techo-Bloc, Unilock, Belgard)",
      "Natural fieldstone",
      "Brick paver",
    ],
    durationTypical: "5–10 working days for a 300–600 sq ft patio",
    costRange: "$45–$85 per square foot installed, materials and base included",
    bestSeason: "April through November (we work earlier and later when weather permits)",
    lifespan: "30–50+ years with proper base prep",
    regulatoryNote: "Most patios under 200 sq ft do not require a permit, but conservation, wetlands, and historic district overlays apply in many MA towns",
    inspectionPoints: [
      "Base depth and compaction (minimum 6\" of compacted ¾\" crushed stone)",
      "Geotextile separator between subgrade and base",
      "Slope (1/8\" per foot minimum away from structures)",
      "Joint sand: polymeric only — never plain sand",
      "Edge restraint installed properly",
    ],
    whyNow: "Massachusetts freeze-thaw cycles compound damage every winter. A patio rebuilt before December locks in winter use and avoids the spring rush.",
    faqs: [
      { q: "Do I need a permit for a patio?", a: "In most MA towns, patios under 200 sq ft do not require a permit. Conservation, wetlands, and historic district overlays may apply — we handle permitting when needed." },
      { q: "How long should a properly built patio last?", a: "A patio with engineered base, geotextile separation, and polymeric joint sand will last 30–50+ years with minimal maintenance." },
      { q: "Can you build over my existing patio?", a: "Almost never recommended. Old base material is rarely up to current standards, and overlaying creates trip hazards and drainage problems. Full removal and rebuild is the right approach." },
    ],
  },
  {
    slug: "stone-walls",
    shortLabel: "Stone Wall",
    longLabel: "Hand-Laid Stone Walls",
    searchPhrase: "stone wall builder",
    searchPhrasePlural: "stone walls",
    problems: [
      "Existing fieldstone wall has collapsed sections or leaning courses",
      "Need a new property-line wall that matches historic neighborhood character",
      "Want a freestanding double-faced wall to define a garden or patio",
      "Mortared veneer wall has spalling, cracking, or efflorescence",
      "Old dry-stack wall needs rebuild with proper drainage and ties",
    ],
    materials: [
      "Local Massachusetts fieldstone",
      "New England granite",
      "Pennsylvania flagstone caps",
      "Type S or Type N mortar (matched to existing where applicable)",
      "Geotextile and crushed stone for drainage",
    ],
    durationTypical: "1–3 weeks for 40–80 linear feet depending on height and complexity",
    costRange: "$65–$140 per linear foot installed (depending on height and material)",
    bestSeason: "April through November; mortared work pauses when temperatures stay below 40°F",
    lifespan: "Properly built dry-stack walls last 100+ years; mortared walls 60+ years",
    regulatoryNote: "Walls over 4 feet require an engineered design and permit in most MA towns. Historic districts often require fieldstone matching.",
    inspectionPoints: [
      "Footing depth below frost line (48\" in MA)",
      "Batter (lean back into the slope)",
      "Stone selection by hand — face stones, fillers, hearting separately sorted",
      "Hidden through-stones every 4 feet horizontally",
      "Cap stones mortared or pinned",
    ],
    whyNow: "Stone walls are an asset that appreciates with age — but a wall that's already failing will accelerate damage every freeze cycle. Repair early, save twice.",
    faqs: [
      { q: "What's the difference between dry-stack and mortared walls?", a: "Dry-stack uses no mortar — the wall holds itself together through stone selection and gravity. Mortared walls use mortar between stones for rigid construction. Both have their place; we'll recommend based on use case and aesthetic." },
      { q: "Can you match an existing historic stone wall?", a: "Yes. We sort through fieldstone yards and quarries to match color, texture, and weathering. For mortared walls we can custom-tint mortar to match aged joints." },
      { q: "How long does a stone wall last?", a: "A properly built dry-stack wall lasts 100+ years with minimal maintenance. Mortared walls typically last 60+ years before needing repointing." },
    ],
  },
  {
    slug: "walkways",
    shortLabel: "Walkway",
    longLabel: "Custom Walkways & Front Walks",
    searchPhrase: "walkway installer",
    searchPhrasePlural: "walkways",
    problems: [
      "Existing concrete walkway has cracked, heaved, or settled unevenly",
      "Front walk doesn't match the upgraded look of the house",
      "Walkway is too narrow for two people to walk side-by-side",
      "Pavers have shifted creating trip hazards",
      "Stoop and walkway transition is failing",
    ],
    materials: [
      "Bluestone (irregular or thermal-finished)",
      "Brick paver",
      "Granite cobble",
      "Concrete paver",
      "Natural fieldstone stepping stones",
    ],
    durationTypical: "3–7 days for a typical front walk",
    costRange: "$35–$60 per square foot installed for stone; $25–$40 for concrete",
    bestSeason: "April through November",
    lifespan: "25–40+ years for paver; 50+ years for stone",
    regulatoryNote: "Walks within town right-of-way typically require a sidewalk permit. ADA transitions required at curb cuts.",
    inspectionPoints: [
      "Base depth (4–6\" of compacted ¾\" crushed stone)",
      "Pitch (1/4\" per foot toward landscape, never the house)",
      "Polymeric joint sand or proper mortar joints",
      "Edge restraint",
      "Smooth transition at stoop and driveway",
    ],
    whyNow: "Your walkway is the first thing every visitor sees. A fresh walk increases curb appeal and home value within days of completion.",
    faqs: [
      { q: "How wide should my front walkway be?", a: "Minimum 4 feet, ideally 5 feet to allow two people to walk side-by-side. Estate walks can be 6+ feet wide for proportional balance with larger homes." },
      { q: "What's better — stone or pavers?", a: "Natural stone (bluestone, granite) offers premium curb appeal and longest lifespan. Concrete pavers offer more pattern variety and lower cost. Both are excellent when properly installed." },
      { q: "Will the walkway crack in winter?", a: "Properly installed stone and paver walks won't crack — they flex with freeze-thaw via segmented joints. Poured concrete is the surface most likely to crack." },
    ],
  },
  {
    slug: "chimneys",
    shortLabel: "Chimney",
    longLabel: "Chimney Repair & Rebuild",
    searchPhrase: "chimney contractor",
    searchPhrasePlural: "chimneys",
    problems: [
      "Mortar joints are crumbling and bricks are loose",
      "Chimney crown is cracked, allowing water into the structure",
      "Flashing leaks at the roofline causing water damage inside the house",
      "Brick is spalling (face popping off) from freeze-thaw damage",
      "Chimney is leaning or shows visible structural failure",
    ],
    materials: [
      "Matched salvaged or new brick to suit existing chimney era",
      "Cast-in-place concrete crown or custom precast",
      "Lead step and counter flashing (no rubber substitutes)",
      "Type N or Type S mortar (matched to existing)",
      "Stainless-steel chimney cap",
    ],
    durationTypical: "Repointing: 3–5 days. Full rebuild: 1–2 weeks.",
    costRange: "Repointing: $1,500–$5,000. Crown replacement: $1,200–$3,500. Full rebuild: $4,000–$15,000+",
    bestSeason: "April through November; cold weather slows mortar cure",
    lifespan: "Proper rebuild: 60–100+ years. Repointing extends life by 25+ years.",
    regulatoryNote: "Building permits required for rebuilds in all MA towns. Many require pre/post-inspection. We pull permits and coordinate inspections.",
    inspectionPoints: [
      "Mortar joint depth and pointing technique (raked, struck, or weather-struck per period)",
      "Crown thickness (minimum 2\" with drip edge overhang)",
      "Flashing layered properly (counter over step)",
      "Flue liner condition (we coordinate Level 2 inspections)",
      "Cap installed to prevent moisture and animals",
    ],
    whyNow: "A chimney leak today is a ceiling and wall repair tomorrow. Repointing before winter saves thousands in water damage by spring.",
    faqs: [
      { q: "How do I know if my chimney needs repointing vs full rebuild?", a: "If the brick itself is sound and only mortar joints are eroded, repointing is the right call. If brick is spalling, leaning, or significantly displaced, a partial or full rebuild is needed. We assess in person — no guessing." },
      { q: "Do you pull the permits?", a: "Yes. We pull all required building permits, coordinate with the local building inspector, and provide certificates of completion." },
      { q: "How long does the chimney work last?", a: "A proper rebuild with quality brick and mortar lasts 60–100+ years. Repointing extends life by 25+ years before the next service." },
    ],
  },
  {
    slug: "retaining-walls",
    shortLabel: "Retaining Wall",
    longLabel: "Engineered Retaining Walls",
    searchPhrase: "retaining wall contractor",
    searchPhrasePlural: "retaining walls",
    problems: [
      "Existing wall is leaning, bulging, or showing failed courses",
      "Slope behind house is eroding and threatening foundation",
      "Need terraced gardens or usable yard space on a sloped lot",
      "Driveway edge needs retention to prevent grade collapse",
      "Old railroad-tie wall is rotting and needs permanent replacement",
    ],
    materials: [
      "Segmental block (Versa-Lok, Unilock, Allan Block)",
      "Boulder retaining walls (locally sourced)",
      "Natural stone (fieldstone, granite)",
      "Poured-in-place concrete with stone veneer",
      "Geogrid reinforcement layers",
    ],
    durationTypical: "1–3 weeks depending on length, height, and access",
    costRange: "$60–$150 per square face foot installed",
    bestSeason: "April through November; deep excavation pauses in hard frost",
    lifespan: "Properly engineered walls: 75–100+ years",
    regulatoryNote: "Walls over 4 feet (some towns 3 feet) require engineered drawings and permit. Many MA towns enforce conservation setback rules.",
    inspectionPoints: [
      "Footing depth below frost line (48\")",
      "Drainage tile behind wall (perforated pipe in crushed stone)",
      "Geotextile separator between backfill and native soil",
      "Geogrid reinforcement layers (mandatory above 4 feet)",
      "Backfill compaction in lifts (max 8\" per pass)",
    ],
    whyNow: "A failing retaining wall is a foundation problem waiting to happen. Address it before the next heavy spring rain.",
    faqs: [
      { q: "How tall can a retaining wall be?", a: "We build walls from 2 feet (garden walls) up to 12+ feet (engineered terraces). Walls over 4 feet require an engineer's stamp and permit." },
      { q: "What's the most important part of a retaining wall?", a: "What you can't see — drainage. A wall without proper perforated drain tile, crushed-stone backfill, and geotextile separator will fail within 5–10 years no matter how good the face stone looks." },
      { q: "Can you build into a slope or only against existing soil?", a: "Both. We can cut into a hillside for a benched terrace or build a freestanding wall to create a level yard above grade. Each requires different drainage and structural approach." },
    ],
  },
  {
    slug: "sidewalks",
    shortLabel: "Sidewalk",
    longLabel: "Concrete & Paver Sidewalks",
    searchPhrase: "sidewalk contractor",
    searchPhrasePlural: "sidewalks",
    problems: [
      "Town sidewalk is cracked and creating liability concerns",
      "Commercial sidewalk needs ADA-compliant repour",
      "Existing concrete is heaved and uneven from tree roots",
      "Sidewalk-driveway transition is failing",
      "Need new sidewalk along property frontage",
    ],
    materials: [
      "4,000 PSI concrete with fiber reinforcement",
      "Concrete paver (interlocking)",
      "Brick paver in historic districts",
      "Granite curb and edging",
    ],
    durationTypical: "2–5 days for a typical residential frontage",
    costRange: "$8–$20 per square foot for concrete; $15–$30 for paver",
    bestSeason: "April through November; concrete cures slow in cold",
    lifespan: "Concrete: 25–40 years. Paver: 30–50+ years.",
    regulatoryNote: "Sidewalks in town right-of-way require a permit and town spec compliance. ADA compliance mandatory at curb cuts and driveway transitions.",
    inspectionPoints: [
      "Base depth (4–6\" of compacted ¾\" crushed stone)",
      "Saw-cut control joints (typically every 4–6 feet)",
      "Brushed finish for traction",
      "ADA-compliant slope (1.5% maximum cross-slope)",
      "Detectable warning panels at curb cuts where required",
    ],
    whyNow: "Cracked sidewalks are a slip-and-fall liability. A property owner can be held responsible — fix it before someone gets hurt.",
    faqs: [
      { q: "Do I need a permit?", a: "Yes. Sidewalks in the public right-of-way require a town permit and inspection. We pull all permits and coordinate with town DPW." },
      { q: "Concrete or paver for residential sidewalks?", a: "Concrete is faster and cheaper. Paver looks better and lasts longer. Both meet town spec when installed correctly." },
      { q: "Will my new sidewalk crack?", a: "Saw-cut control joints direct cracking to predictable lines. With proper base prep, you won't see random cracks for 20+ years." },
    ],
  },
  {
    slug: "residential-masonry",
    shortLabel: "Residential Masonry",
    longLabel: "Residential Masonry Services",
    searchPhrase: "residential mason",
    searchPhrasePlural: "residential masonry projects",
    problems: [
      "Front steps and stoop are crumbling or unsafe",
      "Foundation veneer is failing or needs cosmetic upgrade",
      "Interior fireplace and hearth need rebuild or refresh",
      "Outdoor pillars or columns are deteriorating",
      "Need brick or stone matching for additions or renovations",
    ],
    materials: [
      "Brick (matched to existing era)",
      "Natural stone veneer",
      "Cultured stone (manufactured veneer)",
      "Granite stoop treads",
      "Bluestone caps and sills",
    ],
    durationTypical: "Varies by scope — single stoop: 3–5 days. Whole-home veneer: 2–4 weeks.",
    costRange: "Project-specific — get an itemized quote",
    bestSeason: "April through November",
    lifespan: "Quality residential masonry: 60–100+ years",
    regulatoryNote: "Structural masonry requires permits. Cosmetic work typically doesn't.",
    inspectionPoints: [
      "Match existing brick/stone for era and color",
      "Proper flashing and weep system on veneer walls",
      "Footing depth for structural elements",
      "Mortar mix matched to existing for historic homes",
      "Caulking and sealant compatible with masonry",
    ],
    whyNow: "Quality masonry is the difference between a house that looks lived-in and a house that looks loved. The right detail work pays back at resale.",
    faqs: [
      { q: "Can you match my existing brick?", a: "Most of the time, yes. We work with regional brick yards and can custom-tint mortar to match weathered joints. We do test panels before committing to full scope." },
      { q: "Do you do interior work?", a: "Yes. Fireplaces, hearths, indoor accent walls, and basement foundation veneer." },
      { q: "What about additions and renovations?", a: "We coordinate with GCs, architects, and homeowners on additions to ensure new masonry blends seamlessly with existing." },
    ],
  },
  {
    slug: "commercial-masonry",
    shortLabel: "Commercial Masonry",
    longLabel: "Commercial Masonry Services",
    searchPhrase: "commercial mason",
    searchPhrasePlural: "commercial masonry projects",
    problems: [
      "Storefront brick is failing and impacting property value",
      "Commercial walkway needs ADA-compliant repour",
      "Restaurant or retail patio needs cohesive hardscape",
      "Multi-family property has multiple masonry issues to coordinate",
      "Property management needs reliable masonry contractor for ongoing work",
    ],
    materials: [
      "Commercial-grade brick",
      "Natural stone veneer",
      "4,000+ PSI concrete",
      "ADA-compliant detectable warnings",
      "Custom signage stonework",
    ],
    durationTypical: "Project-specific; commercial work typically 2–8 weeks",
    costRange: "Commercial estimates require site visit and detailed scope",
    bestSeason: "Year-round when conditions allow; cold weather work with heated enclosures",
    lifespan: "Commercial-grade masonry: 50–100+ years",
    regulatoryNote: "All commercial work requires permits. ADA compliance is mandatory. We pull permits and coordinate inspections.",
    inspectionPoints: [
      "Code compliance (building, ADA, fire)",
      "Commercial-grade materials throughout",
      "Documented base prep and reinforcement",
      "Coordination with GC and property management",
      "Insurance documentation and certificates",
    ],
    whyNow: "Commercial property condition directly impacts tenant retention and customer perception. Address masonry issues before they become signage problems.",
    faqs: [
      { q: "Are you insured for commercial work?", a: "Yes — fully. Commercial general liability and workers' comp on every employee. Certificates available to property managers and GCs before we set foot on site." },
      { q: "Do you coordinate with general contractors?", a: "Yes. We work as a sub for GCs regularly, coordinate with architects and engineers, and meet town and inspector requirements." },
      { q: "What types of commercial work do you do?", a: "Storefronts, restaurants, multi-family, property management work, retail, light industrial. We pass on highly specialized work (e.g., institutional restoration) when it's not our specialty." },
    ],
  },
  {
    slug: "custom-projects",
    shortLabel: "Custom Project",
    longLabel: "Custom Masonry Projects",
    searchPhrase: "custom mason",
    searchPhrasePlural: "custom masonry projects",
    problems: [
      "Need an outdoor kitchen with grill, counter, and storage",
      "Want a wood-fired pizza oven that performs and looks good",
      "Designing a fire pit area with seating wall",
      "Vision for a water feature, fountain, or formal garden element",
      "Have a unique design that no off-the-shelf solution fits",
    ],
    materials: [
      "Natural stone (custom-sourced)",
      "Refractory brick for fire features",
      "Stainless steel inserts and components",
      "Granite, marble, or bluestone counter slabs",
      "Custom-fabricated steel for trellises and supports",
    ],
    durationTypical: "Project-specific — typically 2–6 weeks",
    costRange: "Custom work pricing depends entirely on scope and materials",
    bestSeason: "April through November",
    lifespan: "Custom builds with quality materials: 30–60+ years",
    regulatoryNote: "Many custom features (especially gas lines and fire features) require permits and inspection. We coordinate.",
    inspectionPoints: [
      "Design consultation with renderings or sketches",
      "Material samples on site for approval",
      "Footing and base prep for permanent features",
      "Utility coordination (gas, electric, water) where needed",
      "Final walk-through before sign-off",
    ],
    whyNow: "A great backyard isn't bought — it's built. Custom masonry transforms a yard into a destination.",
    faqs: [
      { q: "Can you build to my design?", a: "Yes. Bring sketches, Pinterest boards, or rough ideas. We collaborate on design, material selection, and budget — and execute." },
      { q: "What about outdoor kitchens?", a: "Full design and build: grill enclosures, side burners, refrigeration, storage, counters, lighting. We coordinate gas, electric, and plumbing." },
      { q: "Pizza ovens — wood-fired or gas?", a: "Both. Wood-fired is traditional and produces the best results; gas-fired is convenient and easier to use. We help you decide based on your usage." },
    ],
  },
  {
    slug: "hardscape",
    shortLabel: "Hardscape",
    longLabel: "Complete Hardscape Solutions",
    searchPhrase: "hardscape contractor",
    searchPhrasePlural: "hardscape projects",
    problems: [
      "Entire property needs cohesive hardscape design (walks, patio, walls, driveway)",
      "Drainage problems require integrated solution across multiple features",
      "Want a master plan rather than piecemeal projects over years",
      "New construction needs full landscape and hardscape package",
      "Resale prep requires comprehensive curb appeal upgrade",
    ],
    materials: [
      "Coordinated palette of stone, brick, and concrete",
      "Permeable paver systems",
      "Lighting and irrigation conduit rough-in",
      "Drainage tile and dry well systems",
      "Plant-bed edging and natural transitions",
    ],
    durationTypical: "Full property hardscape: 4–12 weeks",
    costRange: "Full property packages: $40,000–$250,000+ depending on scope",
    bestSeason: "April through November; major work can extend into early winter",
    lifespan: "Full hardscape: 30–50+ years",
    regulatoryNote: "Large hardscape projects often trigger conservation, wetland, and stormwater management review. We coordinate.",
    inspectionPoints: [
      "Master plan with all elevations agreed up front",
      "Integrated drainage and runoff design",
      "Material palette consistency across features",
      "Lighting and irrigation coordination",
      "Phased construction to maintain access",
    ],
    whyNow: "Hardscape is a multi-decade investment. Doing it right once — with a master plan — saves money and time over piecemeal projects.",
    faqs: [
      { q: "What's included in a full hardscape package?", a: "Driveway, walkways, patio, retaining walls, stoops and steps, lighting and irrigation conduit, drainage. Whatever your property needs as a cohesive system." },
      { q: "Can you phase the work to manage budget?", a: "Yes. We design the full master plan and phase construction over 1–3 years if needed. Each phase is complete on its own." },
      { q: "Do you coordinate landscape and planting?", a: "We coordinate with landscape designers and install plant-bed edging and grade transitions. We focus on the hard surfaces and structures; planting partners handle softscape." },
    ],
  },
];

export const serviceMetaBySlug = new Map(serviceMeta.map((s) => [s.slug, s]));
